import type { MenuItem } from "../types/menu";

function formatMoney(value: string | number): string { return new Intl.NumberFormat("en-PK", { style: "currency", currency: "PKR", currencyDisplay: "code", maximumFractionDigits: 2 }).format(Number(value)); }
function titleCase(value: string): string { return value.charAt(0).toUpperCase() + value.slice(1); }

interface MenuItemCardProps { item: MenuItem; busy: boolean; onEdit: (item: MenuItem) => void; onDelete: (item: MenuItem) => void; onToggleAvailability: (item: MenuItem) => void; }

export function MenuItemCard({ item, busy, onEdit, onDelete, onToggleAvailability }: MenuItemCardProps) {
  return <article className="flex flex-col rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h2 className="truncate text-lg font-bold text-ink">{item.name}</h2><p className="mt-1 text-sm text-slate-500">{item.description || "No description provided."}</p></div><span className={`shrink-0 rounded-full px-2.5 py-1 text-xs font-semibold ${item.is_active ? "bg-teal-50 text-teal-700" : "bg-slate-100 text-slate-500"}`}>{item.is_active ? "Active" : "Inactive"}</span></div><dl className="mt-5 grid grid-cols-2 gap-x-4 gap-y-4 border-y border-slate-100 py-4"><div><dt className="text-xs font-semibold uppercase tracking-wide text-slate-400">Price</dt><dd className="mt-1 font-semibold text-ink">{formatMoney(item.price)}</dd></div><div><dt className="text-xs font-semibold uppercase tracking-wide text-slate-400">Day</dt><dd className="mt-1 text-sm font-medium text-slate-700">{item.day_of_week}</dd></div><div><dt className="text-xs font-semibold uppercase tracking-wide text-slate-400">Meal type</dt><dd className="mt-1 text-sm font-medium capitalize text-slate-700">{titleCase(item.meal_type)}</dd></div><div><dt className="text-xs font-semibold uppercase tracking-wide text-slate-400">Availability</dt><dd className={`mt-1 text-sm font-semibold ${item.availability ? "text-teal-700" : "text-amber-700"}`}>{item.availability ? "Available" : "Sold Out"}</dd></div></dl><div className="mt-auto flex flex-wrap gap-2 pt-5"><button type="button" disabled={busy} aria-label={`Edit ${item.name}`} className="rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-60" onClick={() => onEdit(item)}>Edit</button><button type="button" disabled={busy || !item.is_active} aria-label={`${item.availability ? "Mark sold out" : "Mark available"}: ${item.name}`} className={`rounded-lg px-3 py-2 text-sm font-semibold disabled:cursor-not-allowed disabled:opacity-60 ${item.availability ? "bg-amber-50 text-amber-700 hover:bg-amber-100" : "bg-teal-50 text-teal-700 hover:bg-teal-100"}`} onClick={() => onToggleAvailability(item)}>{busy ? "Saving…" : item.availability ? "Available" : "Sold Out"}</button><button type="button" disabled={busy} aria-label={`Delete ${item.name}`} className="ml-auto rounded-lg px-3 py-2 text-sm font-semibold text-rose-600 hover:bg-rose-50 disabled:cursor-not-allowed disabled:opacity-60" onClick={() => onDelete(item)}>Delete</button></div></article>;
}
